# Generated by Django 4.0.3 on 2022-03-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
    ]
